FROM node:18.7.0-alpine

RUN apk update
RUN apk upgrade
RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip
RUN apk add --no-cache g++ make

RUN mkdir /app
WORKDIR /app

COPY ./package.json ./package-lock.json ./
RUN npm install

EXPOSE 8000
